baseurl = 'https://glorichi.github.io/'
locale = 'en'
title = '''Chi's Blog'''
theme = 'PaperMod'

[outputs]
home = ['HTML', 'RSS', 'JSON']

[[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = '/search/'
  weight = 10
